### ISSUE TITLE
Map app not working on Android 4.4.4 

### ISSUE THREAD

**Issue by stevegdavis** [sqall01/chasr-android-map#1]
Hi, I cannot get the map app (latest zip file) to run on a tablet running 4.4.4 I get the following server errors (on https://alertr.de/chasr)
I see that you have a minimum requirement of Android 8, are there plans to change this to allow earlier versions?, would be really useful.

For reference.
build.gradle = 
android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "de.alertr.chasrmap"
        minSdkVersion 19
        targetSdkVersion 28
        versionCode 11
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    testImplementation 'junit:junit:4.12'
    implementation 'com.android.support:appcompat-v7:28.0.0'
}

Mode = Live
I/chromium: [INFO:CONSOLE(21)] "Uncaught SyntaxError: Unexpected token function", source: https://alertr.de/chasr//html/js/map_core.js (21)
I/chromium: [INFO:CONSOLE(86)] "Uncaught ReferenceError: parseHashVars is not defined", source: https://alertr.de/chasr//html/js/map_android.js (86)

Mode = Map
I/chromium: [INFO:CONSOLE(21)] "Uncaught SyntaxError: Unexpected token function", source: https://alertr.de/chasr//html/js/map_core.js (21)
            [INFO:CONSOLE(86)] "Uncaught ReferenceError: parseHashVars is not defined", source: https://alertr.de/chasr//html/js/map_android.js (86)

Many Thanks.

**Comment by sqall01** [comment]
Hi,

no there are no plans since Android 8 is the minimum to have the used Webcrypto API. This is the reason you get the error messages.

Cheers,
sqall
